CREATE TABLE [integracion].[PRT_Siniestros](
	[intIdDenuncia] [int] NOT NULL,
	[intNroSiniestro] [int] NULL,
	[intIdDelegacionOrigen] [int] NULL,
	[intIdOrigenDenuncia] [int] NULL,
	[intIdTipoSiniestro] [int] NULL,
	[datFechaAccidente] [datetime] NOT NULL,
	[intIdOrigenAccidente] [int] NULL,
	[chrJornadaDiaAccDe] [char](6) NULL,
	[chrJornadaDiaAccA] [char](6) NULL,
	[chrJornadaHabitualIni] [char](6) NULL,
	[chrJornadaHabitualFin] [char](6) NULL,
	[varPuestoTrabajoAccidente] [varchar](40) NULL,
	[intIdPais] [int] NULL,
	[varDescripcionAccidente] [varchar](400) NULL,
	[varNombreSitio] [varchar](200) NULL,
	[intIdDomicilioAccidente] [int] NULL,
	[intIdFormaAccidente] [int] NULL,
	[intIdZonaAfectada] [int] NULL,
	[intIdGrado] [int] NULL,
	[chrIdAgenteCausante] [char](3) NULL,
	[intIdNaturalezaLesion] [int] NULL,
	[bitSugiereRecupero] [bit] NULL,
	[bitSugiereInvestigacion] [bit] NULL,
	[bitSugiereRechazo] [bit] NULL,
	[intIdConsecuencia] [int] NULL,
	[decPorcIncapacidad] [decimal](6, 3) NULL,
	[varUbicacionActual] [varchar](150) NULL,
	[intIdPrestador] [int] NULL,
	[intIdUsuarioRecepcion] [int] NOT NULL,
	[datFechaRecepcion] [datetime] NOT NULL,
	[intIdUsuarioModi] [int] NOT NULL,
	[datFechaModi] [datetime] NOT NULL,
	[intIdDelegacion] [int] NULL,
	[datFechaGrabDenuncia] [datetime] NOT NULL,
	[intIdUsuarioGrabDen] [int] NOT NULL,
	[datFechaCierreCecap] [datetime] NULL,
	[intIdUsuarioCecap] [int] NULL,
	[intIdCliente] [int] NULL,
	[intIdEstablecimiento] [int] NULL,
	[intIdTelefonoEmpleador] [int] NULL,
	[varEmailEmpleador] [varchar](100) NULL,
	[intIdTelefonoPrestador] [int] NULL,
	[intIdDenunciante] [int] NULL,
	[intIdEstadoSiniestro] [int] NOT NULL,
	[bitDenunciaInternado] [bit] NULL,
	[intIdSiniestroAsociado] [int] NULL,
	[bitMarcadoRecupero] [bit] NULL,
	[intIdTipoAsistencia] [int] NULL,
	[bitTareaHabitual] [bit] NULL,
	[intIdTipoDenunciaWeb] [int] NULL,
	[bitSoloEspecies] [bit] NULL,
	[intIdGestor] [int] NULL,
	[intIdCie10] [int] NULL,
	[intIdMotivoExclusionReserva] [int] NULL,
	[intIdPrestUbicacionActual] [int] NULL,
	[datFechaInicioSuspension] [datetime] NULL,
	[bitModifRILT] [bit] NOT NULL,
	[bitModifRESP] [bit] NOT NULL,
	[bitModifRINC] [bit] NOT NULL,
	[bitReaseguro] [bit] NOT NULL,
	[datFechaCeseILT] [datetime] NULL,
	[intIdMotivoEgresoILT] [int] NULL,
	[datFechaCeseIPP] [datetime] NULL,
	[intIdMotivoEgresoIPP] [int] NULL,
	[datFechaMarcadoRecupero] [datetime] NULL,
	[bitVisto] [bit] NOT NULL,
	[datFechaCierre] [datetime] NULL,
	[bitGeneradoMedPrev] [bit] NOT NULL,
	[bitControlado] [bit] NOT NULL,
	[datFechaUltimoControl] [datetime] NULL,
	[varMotivoControl] [varchar](200) NULL,
	[varDetalleControl] [varchar](200) NULL,
	[bitEstresPostTraumatico] [bit] NULL,
	[bitCierreManual] [bit] NULL,
	[varObservacionSolicCierre] [varchar](200) NULL,
	[intIdusuarioSolicCierre] [int] NULL,
	[datFechaSolicCierre] [datetime] NULL,
	[datfecEstadoSini] [datetime] NULL,
	[datDw] [datetime] NULL,
	[intIdGestorAsistencial] [int] NULL,
	[bitFechaAccidenteControlada] [bit] NULL,
	[chrOpcion] [nchar](1) NULL,
	[bitCronico] [bit] NULL,
	[bitSospechoso] [bit] NOT NULL,
	[bitRecalifica] [bit] NOT NULL,
	[chrJudiciable] [char](1) NULL,
	[datFechaFinRecalificacion] [datetime] NULL,
	[bitEnvioSRT] [bit] NOT NULL,
	[bitViaPublica] [bit] NOT NULL,
	[datfechafintratamiento] [datetime] NULL,
	[bitTratamiento] [int] NULL,
	[bitMarcaSeguimiento] [bit] NULL,
	[bitValuacion] [bit] NOT NULL,
	[bitIntercurrencia] [bit] NULL,
	[bitAutoDenuncia] [bit] NULL,
	[bitTeletrabajo] [bit] NULL,
	[bitPapeleriaCompletada] [bit] NOT NULL,
	[bitExclusionFFEP] [bit] NOT NULL,
    [integracion] char(1) NOT NULL,
    [SiniestroDboId] int NULL
)
GO

ALTER TABLE [integracion].[PRT_Siniestros] ADD CONSTRAINT [DF_integracion_PRT_Siniestros] DEFAULT (('C')) FOR [integracion]
GO